backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: static/assets
public_folder: /images

collections:
  - name: 'blog'
    label: 'Blog'
    folder: 'src/pages/blogPost'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields: # The fields for each document, usually in front matter
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'blog' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      # - { label: "Featured Image", name: "thumbnail", widget: "image" }
      - { label: 'Body', name: 'body', widget: 'markdown' }
