backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: static/assets
public_folder: /assets

collections:
  - name: 'home'
    label: "Home Page"
    folder: 'src/pages/home'
    create: false
    fields: 
      - { label: 'Image 1', name: 'img1', widget: 'img' }
      - { label: 'Image 2', name: 'img2', widget: 'img' }
      - { label: 'Image 3', name: 'img3', widget: 'img' }

  - name: 'blog'
    label: 'Blog'
    folder: 'src/pages/post'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields: # The fields for each document, usually in front matter
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'blog-post' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: "Image", name: "thumbnail", widget: "image" }
      - { label: 'Body', name: 'body', widget: 'markdown' }